server:
  applicationConnectors:
    - type: http
      port: 9094
  adminConnectors:
    - type: http
      port: 9095
  requestLog:
    appenders:
      - type: console
      - type: file
        # The file to which current statements will be logged.
        currentLogFilename: ./logs/api_requests.log

        # When the log file rotates, the archived log will be renamed to this and gzipped. The
        # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
        # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
        archivedLogFilenamePattern: ./logs/api_requests-%d.log.gz

        # The number of archived files to keep.
        archivedFileCount: 5

        # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
        timeZone: UTC

logging:
  level: INFO
  loggers:
    io.dropwizard: DEBUG
  appenders:
    - type: console
    - type: file
      currentLogFilename: ./logs/api_internal.log
      archivedLogFilenamePattern: ./logs/api_internal-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC

web:
  uriPath: /service
  hsts:
    enabled: true
  frame-options:
    enabled: true
  content-type-options:
    enabled: true
  xss-protection:
    enabled: true
  cors:
    allowedOrigins: [ "https://metadatavalidator.metadatacenter.org" ]
    allowedMethods: [ "DELETE","GET","HEAD","POST","PUT" ]
    allowedHeaders: [ "Accept","Authorization","Content-Type","Origin","X-Requested-With" ]
    preflightMaxAge: 30 minutes

general:
  encoding: 'ASCII'

cedarConfig:
  apiKey: ''
  repoBaseUrl: 'https://repo.metadatacenter.org/'
  resourceBaseUrl: 'https://resource.metadatacenter.org/'
  terminologyEndpoint: 'https://terminology.metadatacenter.org/bioportal/integrated-search/'
  maxRetries: 5
  backoffSleepTime: 1000

bioPortalConfig:
  apiKey: ''
  baseUrl: 'https://data.bioontology.org/'

chatGptConfig:
  apiKey: ''
  baseUrl: 'https://api.openai.com/v1/chat/completions'
  model: 'gpt-3.5-turbo'

swagger:
  resourcePackage: org.metadatacenter.spreadsheetvalidator
